language: php

addons:
  apt:
    packages:
      - libxml2-utils
php:
  - 5.6
  - "7.0"
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"
  - "8.0"
  - "nightly"

env:
  matrix:
    - DEPENDENCIES="high"
    - DEPENDENCIES="low"

matrix:
   fast_finish: true
   include:
     - php: 5.3
       dist: precise
       env: DEPENDENCIES="high"
     - php: 5.3
       dist: precise
       env: DEPENDENCIES="low"
     - php: 5.4
       dist: trusty
       env: DEPENDENCIES="high"
     - php: 5.4
       dist: trusty
       env: DEPENDENCIES="low"
     - php: 5.5
       dist: trusty
       env: DEPENDENCIES="high"
     - php: 5.5
       dist: trusty
       env: DEPENDENCIES="low"
   allow_failures:
     - php: nightly

dist: xenial
sudo: false

before_install:
  - composer self-update
  - composer clear-cache

install:
  - if [[ "$DEPENDENCIES" = 'high' ]]; then travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-stable; fi
  - if [[ "$DEPENDENCIES" = 'low' ]]; then travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-stable --prefer-lowest; fi

script:
  - ./phpunit
  - ./phpunit --configuration ./build/travis-ci-fail.xml > /dev/null; if [ $? -eq 0 ]; then echo "SHOULD FAIL"; false; else echo "fail checked"; fi;
  - xmllint --noout --schema phpunit.xsd phpunit.xml
  - xmllint --noout --schema phpunit.xsd tests/_files/configuration.xml
  - xmllint --noout --schema phpunit.xsd tests/_files/configuration_empty.xml
  - xmllint --noout --schema phpunit.xsd tests/_files/configuration_xinclude.xml -xinclude

notifications:
  email: false

